config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :categories do
    resources :tasks, except: [:index]
  end

  root "categories#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  #validations
  validates :name, presence: true, uniqueness: { scope: :user, case_sensitive: false }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category

  validates :name, presence: true
  validates :target_completion_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable, :rememberable

  has_many :categories, dependent: :destroy
  has_many :tasks, through: :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  def index
    @categories = current_user.categories
    @due_date_today = current_user.tasks.where(target_completion_date: Date.today)
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = current_user.categories.build(category_params)

    if @category.save
      flash[:notice] = "Category created successfully!"
      redirect_to root_path
    else
      flash[:alert] = "Problem adding a category. Please try again."
      render :new, status: 422
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to @category, notice: "Category updated successfully.", status: :see_other
    else
      flash[:alert] = "Problem editing the category. Please try again."
      render :edit, status: 422
    end
  end

  # DELETE /categories/1
  def destroy
    if @category.destroy
      flash[:alert] = "Category deleted permanently."
      redirect_to categories_path, status: :see_other
    else
      flash[:alert] = "Problem deleting the category. Please try again."
      render :index, status: 422
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = current_user.categories.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Path invalid. Make sure your link is correct."
    redirect_to root_path
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_category
  before_action :set_task, only: [:show, :edit, :update]

  def show
    redirect_to category_path(@category)
  end

  def new
    redirect_back(fallback_location: root_path)
  end

  def edit
  end

  def create
    @task = @category.tasks.build(task_params)

    if @task.save
      redirect_to category_path(@category)
      flash[:notice] = 'Task created successfully.'
    else
      redirect_back(fallback_location: root_path)
      flash[:alert] = 'Failed to create the task. Please try again.'
    end
  end

  def update
    if @task.update(task_params)
      redirect_back(fallback_location: root_path)
      flash[:notice] = 'Task updated successfully.'
    else
      flash[:alert] = 'Failed to edit the task. Please try again.'
      render :edit, status: 422
    end
  end

  def destroy
    @task = @category.tasks.find(params[:id])
    @task.destroy
    redirect_back(fallback_location: root_path)
    flash[:notice] = 'Task deleted successfully.'
  end

  private

  def set_category
    @category = current_user.categories.find(params[:category_id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Path invalid. Make sure your link is correct."
    redirect_to root_path
  end

  def set_task
    @task = current_user.tasks.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Path invalid. Make sure your link is correct."
    redirect_to root_path
  end


  def task_params
    params.require(:task).permit(:name, :description, :completed, :target_completion_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_date(date)
    date.strftime("%B #{date.day.ordinalize}, %Y")
  end

  def remove_domain_from_email(email)
    email.gsub(/@.+$/, '')
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <hr class="m-6">
  <div class="flex items-center px-6 gap-4 justify-between">
    <%= category.name %>
    <div>
      <%= link_to "Add Tasks", new_category_task_path(category), class: "rounded-lg py-3 px-5 bg-green-100 inline-block font-medium text-center" %>
      <%= link_to edit_category_path(category), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" do %>
        <i class="fa-solid fa-pen-to-square"></i>
      <% end %>
    </div>
    <% @category.tasks.each do |task| %>
      <%= render partial: 'task', locals: { category: @category, task: task } %>
    <% end %>
  </div>
  <hr class="m-6">
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% category.errors.each do |error| %>
          <li>❌ <%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-5">
    <%= form.label :name, class: "font-thin"  %>
    <%= form.text_field :name, class: "rounded-lg w-full border-2 border-slate-800" %>
  </div>
  <div class="flex flex-col">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-green-300 font-medium cursor-pointer text-center" %>
    <%= link_to "Back", :back, class: "rounded-lg py-3 px-5 font-medium text-center" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="flex flex-col justify-center mx-auto w-3/4 sm:w-1/3 mt-6 bg-slate-200 rounded-lg p-4">
  <h1 class="font-bold text-4xl">Edit category</h1>
  <%= render "form", category: @category %>
</div>

app/views/categories/index.html.erb
<div class="mt-6 w-full">
  <div class="flex justify-between items-center px-4 gap-4">
    <h1 class="font-bold text-4xl">Hello, <%= "#{remove_domain_from_email(current_user.email)} !"%></h1>
    <%= link_to "Create category", new_category_path, class: "rounded-lg text-center py-3 px-5 bg-blue-800 text-white block font-medium" %>
  </div>
</div>
<!--#################### --->
<!--########Today's Task######### --->
<hr class="m-4">
<% unless @categories.empty? %>
  <div class="mb-4">
    <h1 class="text-2xl font-semibold">Due Tasks for Today</h1>
  </div>
  <div class="flex gap-4 flex-wrap items-center justify-center px-4">
    <% if @due_date_today.empty? %>
      <span class="italic font-light">- No task due today! 👍 -</span>
    <% else %>
      <% @due_date_today.where(completed: false).each do |todo| %>
        <%= render partial: 'tasks/due_task',locals: { todo: todo } %>
      <% end %>
    <% end %>
  </div>
<% end %>
<!--####### DISPLAY CATEGORIES ############# --->
<div class="flex flex-wrap justify-center gap-4 mt-6 w-full ">
  <% if @categories.empty? %>
    <div class="flex items-center justify-center">
      <span class="italic font-light">- Create your cagetory 👆 -</span>
    </div>
  <% else %>
    <% @categories.each do |category| %>
      <div class="flex flex-col rounded-lg ">
        <div class="flex justify-between items-center bg-slate-800 p-4 rounded-t-lg shadow-sm w-96 max-h-96 gap-2">
          <div class="font-extrabold text-2xl text-slate-50 truncate" >
            <%= link_to category, class: "truncate" do %>
              <%= category.name %>
            <% end %>
          </div>
          <div class="flex items-center gap-2">
            <%= link_to category_path(category), class: "rounded-lg focus:outline-none text-white bg-green-400 hover:bg-green-500 focus:ring-4 focus:ring-green-300 rounded-lg text-sm dark:focus:ring-green-900 py-2 px-4" do %>
              <i class="fa-solid fa-plus"></i>
            <% end %>
            <%= link_to edit_category_path(category), class: "rounded-lg focus:outline-none text-white bg-yellow-400 hover:bg-yellow-500 focus:ring-4 focus:ring-yellow-300 rounded-lg text-sm dark:focus:ring-yellow-900 py-2 px-4" do %>
              <i class="fa-solid fa-pen-to-square"></i>
            <% end %>
            <%= button_to category_path(category), method: :delete, class: "rounded-lg focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 rounded-lg text-sm dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900 py-2 px-4", data: {
                  turbo_confirm: "Delete #{category.name} category?"
                } do %>
              <i class="fas fa-trash"></i>
            <% end %>
          </div>
        </div>
        <!--####### DISPLAY TASKS ############# --->
        <div class="flex flex-col justify-between bg-slate-200 p-4 rounded-b-lg shadow-sm gap-2 w-96 max-h-96 truncate">
          <% if category.tasks.empty? %>
            <div class="flex items-center justify-center">
              <span class="italic font-light">- No Tasks -</span>
            </div>
          <% else %>
            <%= render partial: 'tasks/task', collection: category.tasks %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<!--#################### --->

app/views/categories/new.html.erb
<div class="flex flex-col justify-center mx-auto w-3/4 sm:w-1/3 mt-6 bg-slate-200 rounded-lg p-4">
  <h1 class="font-bold text-4xl">New category</h1>
  <div>
    <%= render "form", category: @category %>
  </div>
</div>

app/views/categories/show.html.erb
<!--####### DISPLAY CATEGORY ############# --->
<div class="flex flex-col w-5/6 mt-6">
  <div class="bg-slate-800 p-4 rounded-t-lg shadow-sm ">
    <div class="flex justify-between items-center gap-6">
      <h1 class="text-2xl font-extrabold text-slate-50"><%= @category.name %></h1>
      <div class="flex gap-2">
        <%= link_to edit_category_path(@category), class: "rounded-lg focus:outline-none text-white bg-yellow-400 hover:bg-yellow-500 focus:ring-4 focus:ring-yellow-300 rounded-lg text-sm dark:focus:ring-yellow-900 py-2 px-4" do %>
          <i class="fa-solid fa-pen-to-square"></i>
        <% end %>
        <%= button_to category_path(@category), method: :delete, class: "rounded-lg focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 rounded-lg text-sm dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900 py-2 px-4", data: {
                  turbo_confirm: "Delete #{@category.name} category?"
                } do%>
          <i class="fas fa-trash"></i>
        <% end %>
      </div>
    </div>
  </div>
  <div class="flex flex-col sm:flex-row bg-slate-200 rounded-b-lg shadow-sm">
    <div class="flex items-center justify-center w-full sm:w-1/3 p-4 ">
      <%= render partial: 'tasks/new_task', locals: {task: @category.tasks.build } %>
    </div>
    <!--####### DISPLAY TASKS ############# --->
    <div class="w-full sm:w-1/3">
      <div class="flex flex-col justify-between p-4 gap-2">
        <span class="font-bold">TO DO</span>
        <% if @category.tasks.empty? %>
          <div class="flex items-center justify-center">
            <span class="italic font-light">-- No Tasks --</span>
          </div>
        <% else %>
          <%= render partial: 'tasks/task', collection: @category.tasks.where.not(id: nil).where(completed: false) %>
        <% end %>
      </div>
    </div>
    <div class="w-full sm:w-1/3">
      <div class="flex flex-col justify-between p-4 gap-2">
        <span class="font-bold">COMPLETED</span>
        <% if @category.tasks.empty? %>
          <div class="flex items-center justify-center">
            <span class="italic font-light">-- No Completed Tasks Yet--</span>
          </div>
        <% else %>
          <%= render partial: 'tasks/task', collection: @category.tasks.where.not(id: nil).where(completed: true) %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_flash_msg.html.erb
<!-- <div class="fixed bottom-5 right-5 z-30 ">
  <% flash.each do |type, message| %>
    <% if type == "notice" %>
      <div data-controller="flash" data-target="flash.flash" class="flash notice py-2 px-4 bg-green-50 mb-5 text-green-500 font-medium rounded-lg shadow-md">
        <%= message %>
      </div>
    <% else %>
      <div data-controller="flash" data-target="flash.flash" class="flash alert py-2 px-4 bg-red-50 mb-5 text-red-500 font-medium rounded-lg shadow-md">
        <%= message %>
      </div>
    <% end %>
  <% end %>
</div> -->
<% if flash.present? %>
  <% flash.each do |type, message| %>
    <% if type == "notice" %>
      <div 
      data-controller="notification"
      data-notification-delay-value="2000"
      data-transition-enter-from="opacity-0"
      data-transition-enter-to="opacity-100"
      data-transition-leave-from="opacity-100"
      data-transition-leave-to="opacity-0"
      class="transition transform duration-1000 absolute bottom-5 right-5 z-30 py-2 px-4 bg-green-50 mb-5 text-green-500 font-medium rounded-lg shadow-md">
        <%= message %>
      </div>
    <% else %>
      <div 
      data-controller="notification"
      data-notification-delay-value="2000"
      data-transition-enter-from="opacity-0"
      data-transition-enter-to="opacity-100"
      data-transition-leave-from="opacity-100"
      data-transition-leave-to="opacity-0"
      class="transition transform duration-1000 absolute bottom-5 right-5 z-30 py-2 px-4 bg-red-50 mb-5 text-red-500 font-medium rounded-lg shadow-md">
        <%= message %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMinder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path("data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🧠</text></svg>") %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="relative w-full min-h-dvh h-screen bg-slate-50">
    <%= render partial: 'layouts/flash_msg' %>
    <nav class="flex items-center justify-between h-16 px-6 py-3 bg-slate-800">
      <%= link_to "🧠 RailsMinder", root_path, class: "text-slate-50 font-bold text-xl md:text-3xl" %>
      <div class="flex items-center gap-6 text-slate-50 font-bold ">
        <% if current_user.present? %>
          <%= link_to edit_user_registration_path do %>
            <div class="flex items-center gap-4 text-lg md:text-2xl">
              <i class="fa-solid fa-user "></i>
              <span><%= remove_domain_from_email(current_user.email)%></span>
            </div>
          <% end %>
          <%= button_to "Logout", destroy_user_session_path, class: "px-4 py-2 bg-blue-900 rounded-lg",  
                  method: :delete, data: {
                  turbo_confirm: "Leave RailsMinder?" 
                }%>
        <% end %>
      </div>
    </nav>
    <main class="container mx-auto flex flex-col items-center">
      <%= yield %>
    </main>
  </body>
</html>

app/views/tasks/_due_task.html.erb
<div class="flex flex-col bg-red-200 rounded-lg p-4 border-2 border-slate-800">
  <span class="italic font-light text-xs"><%= todo.category.name %></span>
  <span class="text-xl font-bold"><%= todo.name %></span>
</div>

app/views/tasks/_new_task.html.erb
<div class="w-full space-y-2">
  <h1 class="font-bold text-xl pb-2">Add task to <%= @category.name %>:</h1>
  <div class="w-full">
    <%= form_with model: [ @category, task ] do |form| %>
      <% if task.errors.any? %>
        <ul class="font-bold pb-4">
          <% task.errors.full_messages.each do |message| %>
            <li class="text-red-400">❌ <%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="w-full h-full flex flex-col justify-center gap-3">
      <div class="h-full w-full flex flex-col gap-2">
        <div class="flex flex-col">
          <%= form.label :name, "Name:", class: "font-thin" %>
          <%= form.text_field :name, class: "rounded-lg w-full border-2 border-slate-800" %>
        </div>
        <div class="flex flex-col">
          <%= form.label :target_completion_date, "Due Date:", class: "font-thin" %>
          <%= form.date_field :target_completion_date, class: "rounded-lg w-full border-2 border-slate-800" %>
        </div>
      </div>
      <div>
        <%= form.button "Create Task", class: "rounded-lg bg-green-300 py-3 px-6 font-bold w-full text-center cursor-pointer" %>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/tasks/_task.html.erb
<%= form_with model: task, url: [task.category, task], class: "contents", method: :patch do |form| %>
  <div class="flex justify-between bg-slate-300 rounded-lg shadow-sm border-2 border-slate-800 gap-2">
    <div class="flex items-center gap-2 truncate">
      <div class="pl-4">
        <%= form.check_box :completed, as: :boolean, onchange: "this.form.submit()", class: "appearance-none w-4 h-4 border-2 border-slate-800 rounded-full bg-white border" %>
      </div>
      <div class="<%= task.completed ? "truncate italic line-through " : "truncate" %>">
        <%= task.name %>
      </div>
    </div>
    <div class="flex items-center gap-2 py-2 pr-4">
      <%= link_to edit_category_task_path(task.category_id, task.id) do %>
        <i class="fa-regular fa-pen-to-square"></i>
      <% end %>
      <%= link_to [task.category, task], data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this task?"} do %>
        <i class="fa-solid fa-trash-can text-red-500"></i>
      <% end %>
    </div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="flex flex-col justify-center mx-auto w-3/4 sm:w-1/3 mt-6 bg-slate-200 rounded-lg p-4">
  <div class="pb-6">
    <h1 class="text-2xl font-bold">Edit task: <span class="text-lg font-normal"><%= @task.name %></span></h1>
  </div>
  <div class="w-full">
    <%= form_with model: @task, url: category_task_path(@category, @task), method: :patch do |form| %>
      <div class="w-full h-full flex flex-col justify-center gap-4">
        <% if @category.errors.any? %>
          <div class="flex flex-col justify-center">
            <% @category.errors.full_messages.each do |message| %>
              <p class="text-red-500 lowercase font-semibold">
                <%= message %>
              </p>
            <% end %>
          </div>
        <% end %>
        <div class="h-full w-full flex flex-col gap-2">
          <div class="">
            <%= form.label :name, "Task:", class: "font-thin" %>
            <%= form.text_field :name, class: "rounded-lg w-full border-2 border-slate-800"  %>
          </div>
          <div class="">
            <%= form.label :target_completion_date, "Due Date:", class: "font-thin" %>
            <%= form.date_field :target_completion_date, class: "rounded-lg w-full border-2 border-slate-800"  %>
          </div>
          <div class="">
            <%= form.check_box :completed, as: :boolean, class: "appearance-none w-4 h-4 border-2 border-slate-800 rounded-full bg-white border"  %>
            <%= form.label :completed, "Done", class: "font-thin"  %>
          </div>
        </div>
        <div class="flex flex-col">
          <%= form.button "Update Task", class: "rounded-lg py-3 px-5 bg-green-300 font-medium cursor-pointer" %>
          <%= link_to "Back to category", category_path(@category), class: "rounded-lg py-3 px-5 font-medium text-center" %>
          <%= link_to "Home", root_path, class: "rounded-lg py-3 px-5 font-medium text-center" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<h1><%= @category.name %></h1>
<h1><%= @task.name %></h1>
<h1><%= @task.description %></h1>
<div class="flex gap-2">
  <div class="bg-slate-600 text-white px-4 py-2 rounded-lg">
    <%= link_to 'BACK', category_path(@category) %>
  </div>
  <div class="bg-red-600 text-white px-4 py-2 rounded-lg">
    <%= link_to "Delete", [@task.category, @task], data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this task?"} %>
  </div>
</div>